const routes = [
    {
        title:'首页',
        key:'/main/index',
    },
    {
        title:'博客管理',
        key:'/blog',
        children:[
            {
                title:'博客列表',
                key:'/main/blog/list'
            },
            {
                title:'新增博客',
                key:'/main/blog/add'
            },
        ]
    },
    {
        title:'案列',
        key:'/main/demo',
        children:[
            {
                title:'万花筒',
                key:'/main/demo/circle'
            },
            {
                title:'基础动画',
                key:'/main/demo/baseDonghua'
            }
        ]
    },
    {
        title:'地图',
        key:'/admin/map',
        children:[
            {
                title:'地图查看',
                key:'/admin/map/query'
            },
            {
                title:'地图介绍',
                key:'/admin/map/des'
            }
        ]
    }
]

export default routes
